; ------------- equals -------------
PAL_MODE equ 0
DMA_IN_PROGRESS equ 1
HBLANKING equ 2
VBLANKING equ 3
ODD_FRAME equ 4
SPRITE_COLLISION equ 5
SPRITE_OVERFLOW equ 6
VBLANK_PENDING equ 7
FIFO_FULL equ 8
FIFO_EMPTY equ 9
Level_Group_2_Size equ 1               ; XREF: sub_8D83E+52/s
Level_Group_10_Size equ 1              ; XREF: sub_8D83E:loc_8DA10/s
Level_Group_11_Size equ 2              ; XREF: sub_8D83E+1D4/s
Level_Group_6_Size equ 3               ; XREF: sub_8D83E+100/s
Level_Group_7_Size equ 3               ; XREF: sub_8D83E+128/s
Level_Group_8_Size equ 3               ; XREF: sub_8D83E+156/s
Level_Group_5_Size equ 4               ; XREF: sub_8D83E+D8/s
Level_Group_4_Size equ 6               ; XREF: sub_8D83E+AA/s
Level_Group_1_Size equ 7               ; XREF: sub_8D83E+26/s
Level_Group_9_Size equ 7               ; XREF: sub_8D83E+17E/s
Level_Group_3_Size equ $B              ; XREF: sub_8D83E+7A/s
; ----------------------------------



